export enum GeneralMessage {
  HEALTHY = 'HEALTHY',
  HEADLESS_UNHEALTHY = 'HEADLESS_UNHEALTHY',
}

export enum ValidationMessage {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export enum AuthMessage {
  MISSING_SERVICE_TOKEN = 'MISSING_SERVICE_TOKEN',
  INVALID_SERVICE_TOKEN = 'INVALID_SERVICE_TOKEN',
}

export enum LobbyMessage {
  LOBBY_FETCHED = 'LOBBY_FETCHED',
  JOINED = 'JOINED',
  LEFT = 'LEFT',
  INVALID_LOBBY_CODE = 'INVALID_LOBBY_CODE',
  LOBBY_NOT_FOUND = 'LOBBY_NOT_FOUND',
  ALREADY_IN_LOBBY = 'ALREADY_IN_LOBBY',
  LOBBY_WAIT_TOO_LONG = 'LOBBY_WAIT_TOO_LONG',
  NOT_IN_LOBBY = 'NOT_IN_LOBBY',
  UNKNOWN_LOBBY_ERROR = 'UNKNOWN_LOBBY_ERROR',
  NOT_OWNER = 'NOT_OWNER',
  READY = 'READY',
  NO_AVAILABLE_MACHINE = 'NO_AVAILABLE_MACHINE',
  ALREADY_OWNS_LOBBY = 'ALREADY_OWNS_LOBBY',
}

export enum GameMessage {
  FINISHED = 'FINISHED',
  NOT_IN_GAME = 'NOT_IN_GAME',
  NO_AVAILABLE_MACHINE = 'NO_AVAILABLE_MACHINE',
  NOT_OWNER = 'NOT_OWNER',
  UNKNOWN_SAVE_ERROR = 'UNKNOWN_SAVE_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}

export enum PlayerMessage {
  PROFILE_FETCHED = 'PROFILE_FETCHED',
  PROFILE_HISTORY_FETCHED = 'PROFILE_HISTORY_FETCHED',
  PROFILE_LINKED = 'PROFILE_LINKED',
  INGAME_ID_ALREADY_LINKED = 'INGAME_ID_ALREADY_LINKED',
}

export enum MachineMessage {
  MACHINE_CREATED = 'MACHINE_CREATED',
  MACHINE_DELETED = 'MACHINE_DELETED',
  UNKNOWN_MACHINE_ERROR = 'UNKNOWN_MACHINE_ERROR',
}

export enum TaskMessage {
  TASK_ACCEPTED = 'TASK_ACCEPTED',
  TASK_STATUS = 'TASK_STATUS',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_ENQUEUE_FAILED = 'TASK_ENQUEUE_FAILED',
}

export enum TaskStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export type ApiResponseMessage =
  | GeneralMessage
  | ValidationMessage
  | AuthMessage
  | LobbyMessage
  | GameMessage
  | PlayerMessage
  | MachineMessage
  | TaskMessage;
